### ISSUE TITLE
.gitignore blocks core Icon directory

### ISSUE THREAD

**Issue by mortona42** [pantheon-systems/example-drops-8-composer#140] opened 2018-03-17 01:55 UTC
https://github.com/pantheon-systems/example-drops-8-composer/blob/7e1c3cfcff4d729c9d33d5c3565da88686f6d543/.gitignore#L91

The Icon rule is blocking this directory:
/core/lib/Drupal/Core/Layout/Icon/

**Comment by stevector** [comment] 2018-03-17 15:33
@mortona42 the gitignore is structured to ignore everything in core: https://github.com/pantheon-systems/example-drops-8-composer/blob/7e1c3cfcff4d729c9d33d5c3565da88686f6d543/.gitignore#L8

The gitignore is set up to ignore anything brought in via composer on this github repo. The build process that does a git force add to add everything to the repo that is pushed to Pantheon.

**Comment by greg-1-anderson** [comment] 2018-03-17 16:45
This might still affect folks who run `prepare-for-pantheon` and maintain their Composer dependencies locally. It also appears that [this .gitignore directive is also in drops-8](https://github.com/pantheon-systems/drops-8/blob/master/.gitignore#L48) (although it does not seem to have prevented the update script from [including the Icon directory in the repository](https://github.com/pantheon-systems/drops-8/tree/master/core/lib/Drupal/Core/Layout/Icon)).

Some adjustment here is probably in order.

**Comment by stevector** [comment] 2018-09-10 15:10
Closing as a duplicate of https://github.com/pantheon-systems/example-drops-8-composer/issues/156

**Closed by stevector** 2018-09-10 15:10 UTC
