### ISSUE TITLE
Documentation: Note that drush_version must be specified in pantheon.yml if not using Drush 8

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/example-drops-8-composer#401] opened 2020-06-17 14:19 UTC
Using this repo with Drush 10, I started getting a weird error yesterday after my Pantheon site got "compute optimized":

```
Could not load SQL class. There is a mismatch between your Drupal [error]
root and your PHP autoloading.
This can happen if you mix Drupal 8 and Drupal 7. [error]
Please check that the location of Drush matches the Drupal core [error]
version you want Drush to talk to.
Drupal\Core\DependencyInjection\ContainerNotInitializedException: [error]
\Drupal::$container is not initialized yet. \Drupal::setContainer()
must be called with a real container. in
/code/web/core/lib/Drupal.php:130
Stack trace:

    /code/web/core/lib/Drupal.php(158): Drupal::getContainer()
    /code/web/core/includes/install.inc(84):
    Drupal::service(‘extension.list….’)
    /opt/pantheon/drush/commands/core/drupal/update.inc(135):
    drupal_load_updates()
    /opt/pantheon/drush/commands/core/core.drush.inc(466):
    update_main()
    /opt/pantheon/drush/includes/command.inc(422):
    drush_core_updatedb()
    /opt/pantheon/drush/includes/command.inc(231):
    _drush_invoke_hooks(Array, Array)
    /opt/pantheon/drush/includes/command.inc(199): drush_command()
    /opt/pantheon/drush/lib/Drush/Boot/BaseBoot.php(67):
    drush_dispatch(Array)
    /opt/pantheon/drush/includes/preflight.inc(67):
    Drush\Boot\BaseBoot→bootstrap_and_dispatch()
    /opt/pantheon/drush/drush.php(12): drush_main()
    {main}
    [notice] Command: *****.pr-15 — drush updatedb [Exit: 1] [error]

```

Pantheon support gave me the solution: to specify `drush_version: 10` in pantheon.yml.  This should be noted in the repo documentation because it's not intuitive at all.

**Comment by radimklaska** [comment] 2020-07-20 20:31
Thanks for publishing that. Adding `drush_version: 10` in `pantheon.yml` fixed the problem for me too.

btw I've seen this error with on two projects with drush 10.3.1 and 10.3.0. Both I think worked before the weekend and started throwing the mentioned error today.

**Comment by michfuer** [comment] 2021-03-17 00:24
Yes, thanks for posting this. I had no `drush_version` set in `pantheon.yml`, and one multi-dev was running drush 9 just fine. A new multi-dev was created from https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.ci/deploy/pantheon/dev-multidev#L20

and I saw the same error. For some reason that multi-dev was running drush 8.

Adding `drush_version: 9` to `pantheon.yml` resolved it for me.

**Comment by damienmckenna** [comment] 2021-05-20 15:41
FYI I've ran into a problem where Drush doesn't properly update, it seems to be stuck on Drush 8.

**Comment by greg-1-anderson** [comment] 2021-05-20 16:46
Setting `drush_version` to 10 in panthoen.yml shouldn't be a requirement. If you have a site with this problem, check and see if `vendor/bin/drush` is being committed and pushed up to Pantheon. If that's in place, then your site-local Drush should work fine at any version.

If you are having issues upgrading your site-local Drush past Drush 8, it could just be a Composer issue. Removing vendor and/or composer.lock before running `composer update` can solve problems related to Composer just being confused. `composer why-not drush/drush:^10` should be informative if the problem is an actual dependency conflict.

**Comment by michfuer** [comment] 2021-05-21 00:49
So I actually don't have access to the relevant Pantheon repo anymore to confirm, but I'm _pretty_ sure `vendor/bin/drush` was being committed and pushed to Pantheon, and it was Drush 9. The multi-dev was Drush 8.

If the site-local Drush dependency is 9, but the multi-dev environment is using a global Drush (accessed via `terminus drush site.env`) of 8, I guess I would kind of expect it to have some issues because of features in 9 that 8 isn't aware of. If reversed and global Drush was 9, with site-local at 8 then I think it would be ok.

**Comment by shaal** [comment] 2021-05-21 03:28
@greg-1-anderson I created a new Drupal 8 website using the build process that utilize `pantheon-systems/drops-8`.
Using `composer`, I upgraded locally to Drupal 9, and Drush 10.
When pushing the new code, I got in CircleCI the error described here https://github.com/pantheon-systems/example-drops-8-composer/issues/401#issue-640481730.

Adding `drush_version: 10` in `pantheon.yml` fixed the problem.

**Comment by damienmckenna** [comment] 2021-05-21 14:27
FWIW my site wouldn't switch to Drush 10 because there was an invisible character in the pantheon.yml file that was not being parsed by Pantheon's systems. I only spotted it when I first downloaded the repository directory (instead of using our build system) and realizing that the changes to pantheon.yml weren't to be found, so when I looked at the build system's output I saw the error message from Pantheon. So, beware invisible characters in your site's pantheon.yml file.

**Comment by greg-1-anderson** [comment] 2021-05-21 16:28
@shaal Can you confirm that your Drupal 9 Build Tools site has a vendor/bin/drush committed in the Pantheon repository?

It's a little surprising that `drush_version: 10` in pantheon.yml would be any sort of a fix for Drupal 9.

1. In theory, if `vendor/bin/drush` exists, Pantheon should call that and not use the global Drush at all
2. The Pantheon global Drush 10 is built for Drupal 8, and blows up on Drupal 9. If the system is passing through the global Drush, one would expect that autoloading the Pantheon global Drush 10 would be destructive to the site-local Drush 10, since they have quite different dependencies.

**Comment by shaal** [comment] 2021-05-21 16:50
@greg-1-anderson The site does not have `vendor/bin/drush` directory committed in the Pantheon repository.

The site was created using 
```
terminus build:project:create --git=github --team='My Agency Name' d8 my-site
```
according to https://pantheon.io/docs/guides/build-tools/create-project

It was created as a Drupal 8 website. I upgraded it to Drupal 9 (and upgraded to Drush 10) using composer.

**Comment by greg-1-anderson** [comment] 2021-05-21 17:34
Figuring out why there is no `vendor/bin/drush` would be a better solution than setting the Drush version in pantheon.yml. That workaround might start failing at any time.

**Comment by kporras07** [comment] 2021-05-28 02:06
I found that this issue was caused because the rsync was not working properly as seen in this screenshot:

<img width="1130" alt="Screen Shot 2021-05-27 at 19 55 26" src="https://user-images.githubusercontent.com/2217820/119919070-e1081d80-bf26-11eb-8580-f038e7cb1460.png">

To fix this, rsync should be used in archive mode (-a).

**Closed** 2021-05-29 00:48 UTC
